# Form implementation generated from reading ui file 'windows_ui/autorization.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 201)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 111, 21))
        self.label.setStyleSheet("font: 12pt \"Calibri\";")
        self.label.setObjectName("label")

        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 70, 307, 105))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.authorize_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.authorize_button.setObjectName("authorize_button")
        self.gridLayout.addWidget(self.authorize_button, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.login_entry = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.login_entry.setObjectName("login_entry")
        self.gridLayout.addWidget(self.login_entry, 0, 1, 1, 1)
        self.password_entry = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_entry.setObjectName("password_entry")
        self.gridLayout.addWidget(self.password_entry, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.warning_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.warning_label.setEnabled(True)
        self.warning_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 11pt;")
        self.warning_label.setObjectName("warning_label")
        self.gridLayout.addWidget(self.warning_label, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизація"))
        self.label.setText(_translate("MainWindow", "Авторизація"))
        self.authorize_button.setText(_translate("MainWindow", "Увійти"))
        self.label_2.setText(_translate("MainWindow", "Логін"))
        self.label_3.setText(_translate("MainWindow", "Пароль"))
        self.warning_label.setText(_translate("MainWindow", "Введені неправильні дані авторизації"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
